# Generated by Django 5.0.4 on 2024-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_images',
            name='user_image',
            field=models.ImageField(default=None, upload_to='', verbose_name='/media'),
            preserve_default=False,
        ),
    ]
